---
sidebar: sidebar 
permalink: data-analytics/confluent-kafka-conclusion.html 
keywords: conclusion 
summary: Este documento fornece diretrizes de práticas recomendadas para usar o Kafka com armazenamento NetApp , incluindo testes de certificação do Confluent Kafka, resultados de desempenho, ajuste, conectores Kafka e o recurso de auto-rebalanceamento. 
---
= Conclusão
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este documento fornece diretrizes de práticas recomendadas para usar o Confluent Tiered Storage com o armazenamento NetApp , incluindo testes de verificação, resultados de desempenho de armazenamento em camadas, ajuste, conectores Confluent S3 e o recurso de autobalanceamento.  Considerando as políticas de ILM, o desempenho do Confluent com vários testes de desempenho para verificação e as APIs S3 padrão do setor, o armazenamento de objetos NetApp StorageGRID é uma escolha ideal para o armazenamento em camadas do Confluent.



== Onde encontrar informações adicionais

Para saber mais sobre as informações descritas neste documento, revise os seguintes documentos e/ou sites:

* O que é Apache Kafka
+
https://www.confluent.io/what-is-apache-kafka/["https://www.confluent.io/what-is-apache-kafka/"^]

* Documentação do produto NetApp
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]

* Detalhes do parâmetro S3-sink
+
https://docs.confluent.io/kafka-connect-s3-sink/current/configuration_options.html["https://docs.confluent.io/kafka-connect-s3-sink/current/configuration_options.html#s3-configuration-options"^]

* Apache Kafka
+
https://en.wikipedia.org/wiki/Apache_Kafka["https://en.wikipedia.org/wiki/Apache_Kafka"^]

* Armazenamento infinito na plataforma Confluent
+
https://www.confluent.io/blog/infinite-kafka-storage-in-confluent-platform/["https://www.confluent.io/blog/infinite-kafka-storage-in-confluent-platform/"^]

* Armazenamento em camadas Confluent - Melhores práticas e dimensionamento
+
https://docs.confluent.io/platform/current/kafka/tiered-storage.html#best-practices-and-recommendations["https://docs.confluent.io/platform/current/kafka/tiered-storage.html#best-practices-and-recommendations"^]

* Conector de coletor Amazon S3 para plataforma Confluent
+
https://docs.confluent.io/kafka-connect-s3-sink/current/overview.html["https://docs.confluent.io/kafka-connect-s3-sink/current/overview.html"^]

* Dimensionamento de Kafka
+
https://eventsizer.io["https://eventsizer.io"]

* Dimensionamento do StorageGRID
+
https://fusion.netapp.com/["https://fusion.netapp.com/"^]

* Casos de uso do Kafka
+
https://kafka.apache.org/uses["https://kafka.apache.org/uses"^]

* Clusters Kafka autobalanceados na plataforma confluente 6.0
+
https://www.confluent.io/blog/self-balancing-kafka-clusters-in-confluent-platform-6-0/["https://www.confluent.io/blog/self-balancing-kafka-clusters-in-confluent-platform-6-0/"^]

+
https://www.confluent.io/blog/confluent-platform-6-0-delivers-the-most-powerful-event-streaming-platform-to-date/["https://www.confluent.io/blog/confluent-platform-6-0-delivers-the-most-powerful-event-streaming-platform-to-date/"^]


