---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-solution.html 
keywords: solution, architecture, details, hardware, software 
summary: Esta seção aborda o hardware e o software usados para a certificação do Dremio.  Estas informações são aplicáveis à implantação do Dremio com armazenamento NetApp . 
---
= Visão geral da solução
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A solução Hybrid Iceberg Lakehouse oferece benefícios exclusivos para abordar os desafios enfrentados pelos clientes do data lake.  Ao aproveitar a plataforma Dremio Unified Lakehouse e as soluções NetApp ONTAP, StorageGRID e NetApp Cloud, as empresas podem agregar valor significativo às suas operações comerciais.  A solução não apenas fornece acesso a várias fontes de dados, incluindo fontes da NetApp , mas também melhora o desempenho analítico geral e ajuda as empresas a gerar insights de negócios que levam ao crescimento dos negócios.



== Visão geral da NetApp

* As ofertas da NetApp, como ONTAP e StorageGRID, permitem a separação de armazenamento e computação, possibilitando a utilização ideal de recursos com base em requisitos específicos.  Essa flexibilidade permite que os clientes dimensionem seu armazenamento de forma independente usando soluções de armazenamento da NetApp
* Ao aproveitar os controladores de armazenamento da NetApp, os clientes podem fornecer dados de forma eficiente para seu banco de dados vetorial usando os protocolos NFS e S3.  Esses protocolos facilitam o armazenamento de dados do cliente e gerenciam o índice do banco de dados vetorial, eliminando a necessidade de múltiplas cópias de dados acessadas por meio de métodos de arquivo e objeto.
* O NetApp ONTAP fornece suporte nativo para NAS e armazenamento de objetos nos principais provedores de serviços de nuvem, como AWS, Azure e Google Cloud.  Essa ampla compatibilidade garante integração perfeita, permitindo mobilidade de dados do cliente, acessibilidade global, recuperação de desastres, escalabilidade dinâmica e alto desempenho.




=== StorageGRID

Nosso armazenamento de objetos líder do setor, o storageGRID, oferece um poderoso mecanismo de política para posicionamento automatizado de dados, opções flexíveis de implantação e durabilidade incomparável com codificação de eliminação em camadas.  Ele tem uma arquitetura escalável que suporta bilhões de objetos e petabytes de dados em um único namespace.  A solução permite a integração de nuvem híbrida, permitindo a hierarquização de dados nas principais plataformas de nuvem.  Ela foi reconhecida como líder na Avaliação de Fornecedores Baseada em Objetos do IDC Marketscape Worldwide de 2019.

Além disso, o storageGRID se destaca no gerenciamento de dados não estruturados em escala com armazenamento de objetos definidos por software, redundância geográfica e recursos multisite.  Ele incorpora gerenciamento de ciclo de vida de informações baseado em políticas e oferece recursos de integração em nuvem, como espelhamento e pesquisa.  Possui diversas certificações, incluindo Common Criteria, NF203 Digital Safe Component, ISO/IEC 25051, KPMG e Cohasset Compliance Assessment.

Em resumo, o NetApp storageGRID oferece recursos poderosos, escalabilidade, integração de nuvem híbrida e certificações de conformidade para gerenciamento eficiente de dados não estruturados em escala.



=== NetApp ONTAP

O NetApp ONTAP é uma solução de armazenamento robusta que oferece uma ampla gama de recursos empresariais.  Inclui o Snapshot, que fornece backups instantâneos consistentes com o aplicativo e à prova de violação.  O SnapRestore permite restauração quase instantânea de backups sob demanda, enquanto o SnapMirror oferece recursos integrados de backup remoto e recuperação de desastres.  A solução também incorpora a Proteção Autônoma contra Ransomware (ARP), garantindo a segurança dos dados com recursos como verificação de vários administradores, criptografia de dados em repouso com certificação FIPS, criptografia de dados em trânsito, autenticação multifator (MFA) e controle de acesso baseado em função (RBAC).  Registro abrangente, auditoria, gerenciamento de chaves internas e externas, limpeza segura e gerenciamento seguro de múltiplos locatários aprimoram ainda mais a segurança e a conformidade dos dados.

O NetApp ONTAP também conta com o SnapLock, que fornece retenção de dados em conformidade com regulamentações, com altos níveis de integridade, desempenho e retenção a um baixo custo total de propriedade.  Ele é totalmente integrado ao NetApp ONTAP 9 e oferece proteção contra atos maliciosos, administradores desonestos e ransomware.

A solução abrange criptografia NSE/NVE para criptografia de dados em voo e em repouso, acesso de administrador multifator e verificação de vários administradores.  O Active IQ fornece análises preditivas e ações corretivas baseadas em IA, enquanto o QoS garante o controle da carga de trabalho de qualidade do serviço.  A integração de gerenciamento e automação é intuitiva por meio de SysMgr/GUI/CLI/API.  O FabricPool permite a hierarquização automática de dados, e a solução oferece eficiência por meio de compactação, desduplicação e compactação de dados em linha.  A NetApp garante o cumprimento das metas de eficiência da carga de trabalho sem nenhum custo para o cliente.

O NetApp ONTAP oferece suporte a vários protocolos, incluindo NVMe/FC, FC, NVMe/TCP, iSCSI, NFS, SMB e S3, o que o torna uma solução de armazenamento unificada.  No geral, o NetApp ONTAP oferece amplos recursos empresariais, segurança robusta, conformidade, eficiência e versatilidade para atender a diversas necessidades de armazenamento.



== Visão geral do Dremio

Dremio é a plataforma Lakehouse unificada para análises de autoatendimento e IA.  A plataforma Dremio Unified Analytics aproxima os usuários dos dados com flexibilidade, escalabilidade e desempenho do lakehouse por uma fração do custo das soluções de data warehouse legadas.  O Dremio permite análises "shift-left" para eliminar a integração de dados complexa e dispendiosa e ETL, proporcionando análises contínuas em escala empresarial sem movimentação de dados.  O Dremio também apresenta:

* Análises de autoatendimento fáceis de usar, possibilitadas por uma camada semântica universal e um mecanismo de consulta SQL altamente integrado e de alto desempenho, facilitando a conexão, o controle e a análise de todos os dados, tanto na nuvem quanto no local.
* Os recursos de gerenciamento de lakehouse nativos do Apache Iceberg do Dremio simplificam a descoberta de dados e automatizam a otimização de dados, oferecendo análises de alto desempenho com controle de versão de dados inspirado no Git.
* Baseado em código aberto e padrões abertos, o Dremio permite que as empresas evitem a dependência e permaneçam posicionadas para a inovação.  Empresas corporativas confiam no Dremio como a plataforma lakehouse mais fácil de usar, com o melhor custo-benefício em todas as cargas de trabalho.




== Que valor a solução Dremio e NetApp Hybrid Iceberg Lakehouse oferece aos clientes?

* *Gerenciamento de dados e acessibilidade aprimorados*: A Dremio é conhecida por sua plataforma de data lakehouse que permite que organizações consultem dados diretamente de seus data lakes em alta velocidade.  A NetApp, por outro lado, é uma provedora líder de serviços de dados em nuvem e soluções de armazenamento de dados.  A oferta conjunta fornece aos clientes uma solução abrangente para armazenar, gerenciar, acessar e analisar os dados de sua empresa de forma eficiente e eficiente.
* *Otimização de desempenho*: Com a experiência da NetApp em armazenamento de dados e os recursos da Dremio em processamento e otimização de dados, a parceria oferece uma solução que melhora o desempenho das operações de dados, reduz a latência e aumenta a velocidade do insight de negócios.  O Dremio até mesmo trouxe benefícios de desempenho para a infraestrutura analítica de TI interna da NetApp.
* *Escalabilidade*: Tanto o Dremio quanto o NetApp oferecem uma solução projetada para escalar.  A solução conjunta fornece aos clientes ambientes de armazenamento, gerenciamento de dados e análise de dados altamente escaláveis.  Em um ambiente Hybrid Iceberg Lakehouse, o mecanismo de consulta Dremio SQL emparelhado com o NetApp StorageGRID oferece escalabilidade, simultaneidade e desempenho de consulta incomparáveis, capaz de lidar com as necessidades analíticas de qualquer negócio.
* *Segurança e governança de dados*: Ambas as empresas têm um forte foco em segurança e governança de dados.  Juntos, eles oferecem recursos robustos de segurança e governança de dados, garantindo que os dados sejam protegidos e que os requisitos de governança de dados sejam atendidos.  Recursos como controles de acesso detalhados e baseados em funções, auditoria abrangente, linhagem de dados de ponta a ponta, gerenciamento unificado de identidade e SSO com uma ampla estrutura de conformidade e segurança garantem que os ambientes de dados analíticos das empresas sejam seguros e governados.
* *Eficiência de custos*: Ao integrar o mecanismo de data lake da Dremio com as soluções de armazenamento da NetApp, os clientes podem reduzir os custos associados ao gerenciamento e à movimentação de dados.  As organizações também podem migrar de ambientes de data lake legados para uma solução de lakehouse mais moderna, composta por NetApp e Dremio.  Esta solução Hybrid Iceberg Lakehouse oferece desempenho de consulta de alta velocidade e simultaneidade de consulta líder de mercado, o que reduz o TCO e o tempo para obter insights de negócios.

