---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-conclusion.html 
keywords: conclusion 
summary: Este documento fornece diretrizes de práticas recomendadas para usar o Dremio com armazenamento NetApp , incluindo testes de certificação TPCDS, ajustes e detalhes de casos de uso do cliente. 
---
= Conclusão
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Concluindo, este relatório técnico forneceu detalhes abrangentes de implantação do q Hybrid Iceberg Lakehouse com Dremio em conjunto com várias fontes de dados de controladores de armazenamento NetApp , incluindo ONTAP S3, NAS e StorageGRID.  O processo de implantação foi executado com sucesso, e a ferramenta de benchmarking TPC-DS foi utilizada para executar 99 consultas SQL nas diferentes fontes de dados.  O relatório também explorou casos de uso de clientes dentro do NetApp, demonstrando a versatilidade e eficácia do Dremio em atender a diversos requisitos de negócios.  Além disso, um caso de uso específico envolvendo um cliente de vendas de peças automotivas foi examinado, destacando a aplicação prática e os benefícios de aproveitar o Dremio para análises de dados e insights.

No geral, este documento serve como um recurso valioso para entender a implantação e o uso do Dremio com controladores de armazenamento NetApp , mostrando seus recursos e potencial para impulsionar a tomada de decisões e a otimização baseadas em dados em vários setores.



== Onde encontrar informações adicionais

Para saber mais sobre as informações descritas neste documento, revise os seguintes documentos e/ou sites:

* Instalação do tratador de zoológico
+
https://medium.com/@ahmetfurkandemir/distributed-hadoop-cluster-1-spark-with-all-dependincies-03c8ec616166[]

* Dremio
+
https://docs.dremio.com/current/get-started/cluster-deployments/deployment-models/standalone/standalone-tarball/[]

* Configurando Dremio com storageGRID
+
https://docs.netapp.com/us-en/storagegrid-enable/tools-apps-guides/configure-dremio-storagegrid.html#configure-dremio-data-source[]

* Caso de uso do NetApp
+
https://www.dremio.com/customers/netapp/[]


