---
sidebar: sidebar 
permalink: data-analytics/kafka-ontap-overview.html 
keywords: tr4941, 4941, introduction 
summary: Este documento descreve benchmarks de desempenho para a plataforma Confluent no NetApp ONTAP usando um kit de benchmarking de armazenamento em camadas. 
---
= TR-4941: Confluente com controladores de armazenamento NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Karthikeyan Nagalingam, Joe Scott, NetApp Rankesh Kumar, Confluente

[role="lead"]
Para tornar a Plataforma Confluent mais escalável e elástica, ela deve ser capaz de dimensionar e balancear cargas de trabalho muito rapidamente.  O armazenamento em camadas torna o armazenamento de grandes volumes de dados no Confluent gerenciável, reduzindo essa carga operacional.

A ideia fundamental é separar o armazenamento de dados do processamento de dados, o que torna muito mais fácil dimensionar cada um de forma independente.

Equipado com inovações líderes do setor, o software de gerenciamento de dados NetApp ONTAP oferece à Confluent muitas vantagens onde quer que os dados estejam.

Este documento descreve benchmarks de desempenho para a plataforma Confluent no NetApp ONTAP usando um kit de benchmarking de armazenamento em camadas.
