---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'netapp, solutions, ai, what"s new, updates, change log' 
summary: Registro de alterações recentes no material de apoio das soluções de inteligência artificial da NetApp . 
---
= Novidades nas soluções de inteligência artificial da NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aprenda o que há de novo em soluções de inteligência artificial.



== 18 de agosto de 2025

O site da NetApp Solutions agora é olink:https://docs.netapp.com/us-en/netapp-solutions-family/index.html["Família de soluções NetApp"^] , que inclui os seguintes sites:

* Soluções de inteligência artificial da NetApp
* link:https://docs.netapp.com/us-en/netapp-solutions-containers/index.html["Soluções de contêiner NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-dataops/index.html["Soluções de gerenciamento de dados da NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-databases/index.html["Soluções de banco de dados NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-cloud/index.html["Soluções de nuvem pública e híbrida da NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-sap/index.html["Soluções NetApp para SAP"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-virtualization/index.html["Soluções de virtualização da NetApp"^]




== 3 de dezembro de 2025

Nova solução:link:software/ai-hybrid-union.html["Implante treinamento híbrido de IA com Union.ai e NetApp FlexCache."]

Utilize a orquestração do Union.ai com o NetApp FlexCache para executar cargas de trabalho de treinamento de IA em GPUs na nuvem, mantendo os dados confidenciais em infraestrutura local.  O FlexCache armazena em cache apenas os dados necessários na nuvem para um treinamento híbrido eficiente e seguro.
