---
sidebar: sidebar 
permalink: infra/ai-lenovo-edge-conclusion.html 
keywords: acknowledgements, additional information 
summary: A automação orientada por IA e a computação de ponta são uma abordagem líder para ajudar organizações empresariais a alcançar a transformação digital e maximizar a eficiência operacional e a segurança.  Com a computação de ponta, os dados são processados muito mais rápido porque não precisam viajar de um data center para outro.  Portanto, o custo associado ao envio e recebimento de dados para data centers ou para a nuvem é reduzido. 
---
= Conclusão
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A automação orientada por IA e a computação de ponta são uma abordagem líder para ajudar organizações empresariais a alcançar a transformação digital e maximizar a eficiência operacional e a segurança.  Com a computação de ponta, os dados são processados muito mais rápido porque não precisam viajar de um data center para outro.  Portanto, o custo associado ao envio e recebimento de dados para data centers ou para a nuvem é reduzido.  Menor latência e maior velocidade podem ser benéficas quando as empresas precisam tomar decisões quase em tempo real usando modelos de inferência de IA implantados na borda.

Os sistemas de armazenamento NetApp oferecem o mesmo desempenho ou melhor que o armazenamento SSD local e oferecem os seguintes benefícios para cientistas de dados, engenheiros de dados, desenvolvedores de IA/ML e tomadores de decisões de negócios ou de TI:

* Compartilhamento fácil de dados entre sistemas de IA, análises e outros sistemas empresariais críticos.  Esse compartilhamento de dados reduz a sobrecarga de infraestrutura, melhora o desempenho e simplifica o gerenciamento de dados em toda a empresa.
* Computação e armazenamento escaláveis de forma independente para minimizar custos e melhorar o uso de recursos.
* Fluxos de trabalho de desenvolvimento e implantação simplificados usando cópias e clones de Snapshot integrados para espaços de trabalho de usuários instantâneos e com economia de espaço, controle de versão integrado e implantação automatizada.
* Proteção de dados de nível empresarial para recuperação de desastres e continuidade de negócios.  A solução da NetApp e da Lenovo apresentada neste documento é uma arquitetura flexível e escalável, ideal para implantações de inferência de IA de nível empresarial na borda.




== Agradecimentos

* JJ  Falkanger, gerente sênior, soluções de HPC e IA, Lenovo
* Dave Arnette, engenheiro de marketing técnico, NetApp
* Joey Parnell, líder técnico de soluções de IA da série E, NetApp
* Cody Harryman, engenheiro de controle de qualidade, NetApp




== Onde encontrar informações adicionais

Para saber mais sobre as informações descritas neste documento, consulte os seguintes documentos e/ou sites:

* Página de produto dos arrays NetApp AFF Série A
+
https://www.netapp.com/data-storage/aff-a-series/["https://www.netapp.com/data-storage/aff-a-series/"^]

* Software de gerenciamento de dados NetApp ONTAP — biblioteca de informações ONTAP 9
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* TR-4727: Introdução à série NetApp EF
+
https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf"^]

* Folha de dados do software NetApp E-Series SANtricity
+
https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf["https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf"^]

* Armazenamento persistente da NetApp para contêineres — NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* MLPerf
+
** https://mlcommons.org/en/["https://mlcommons.org/en/"^]
** http://www.image-net.org/["http://www.image-net.org/"^]
** https://mlcommons.org/en/news/mlperf-inference-v11/["https://mlcommons.org/en/news/mlperf-inference-v11/"^]


* Cópia e sincronização do NetApp BlueXP
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* Benchmark do TensorFlow
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* Servidor Lenovo ThinkSystem SE350 Edge
+
https://lenovopress.com/lp1168["https://lenovopress.com/lp1168"^]

* Matriz de armazenamento flash unificada Lenovo ThinkSystem DM5100F
+
https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array["https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array"]


