---
sidebar: sidebar 
permalink: software/ai-conf-protopia-addtl.html 
keywords:  
summary:  
---
= Onde encontrar informações adicionais e agradecimentos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para saber mais sobre as informações descritas neste documento, consulte os seguintes documentos e/ou sites:

* Software de gerenciamento de dados NetApp ONTAP — biblioteca de informações ONTAP
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* Armazenamento persistente da NetApp para contêineres — NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* Kit de ferramentas NetApp DataOps
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* Armazenamento persistente da NetApp para contêineres — NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* Protopia AI — Inferência Confidencial
+
https://protopia.ai/blog/protopia-ai-takes-on-the-missing-link-in-ai-privacy-confidential-inference/["https://protopia.ai/blog/protopia-ai-takes-on-the-missing-link-in-ai-privacy-confidential-inference/"^]

* Cópia e sincronização do NetApp BlueXP
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* Servidor de inferência NVIDIA Triton
+
https://developer.nvidia.com/nvidia-triton-inference-server["https://developer.nvidia.com/nvidia-triton-inference-server"^]

* Documentação do servidor de inferência NVIDIA Triton
+
https://docs.nvidia.com/deeplearning/triton-inference-server/index.html["https://docs.nvidia.com/deeplearning/triton-inference-server/index.html"^]

* FaceBoxes em PyTorch
+
https://github.com/zisianw/FaceBoxes.PyTorch["https://github.com/zisianw/FaceBoxes.PyTorch"^]





== Agradecimentos

* Mark Cates, gerente de produtos principal, NetApp
* Sufian Ahmad, engenheiro técnico de marketing, NetApp
* Hadi Esmaeilzadeh, Diretor de Tecnologia e Professor, Protopia AI

