---
sidebar: sidebar 
permalink: software/ai-nvaie-vmw-setup.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVAIE, VMware 
summary: NVIDIA AI Enterprise com NetApp e VMware - Configuração inicial 
---
= Configuração inicial
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta seção descreve as tarefas de configuração inicial que precisam ser executadas para utilizar o NVIDIA AI Enterprise com NetApp e VMware.



== Pré-requisitos

Antes de executar as etapas descritas nesta seção, presumimos que você já tenha implantado o VMware vSphere e o NetApp ONTAP.  Consulte olink:https://docs.nvidia.com/ai-enterprise/latest/product-support-matrix/index.html["Matriz de suporte a produtos empresariais NVIDIA AI"^] para obter detalhes sobre as versões suportadas do vSphere.  Consulte olink:https://docs.netapp.com/us-en/netapp-solutions/vmware/index.html["Documentação da solução NetApp e VMware"^] para obter detalhes sobre a implantação do VMware vSphere com o NetApp ONTAP.



== Instalar o software host empresarial NVIDIA AI

Para instalar o software host NVIDIA AI Enterprise, siga as instruções descritas nas seções 1 a 4 dolink:https://docs.nvidia.com/ai-enterprise/latest/quick-start-guide/index.html["Guia de início rápido do NVIDIA AI Enterprise"] .
