---
sidebar: sidebar 
permalink: software/ai-osmlops-trident-backend.html 
keywords: ONTAP, Trident, AI, Deployment, 
summary: MLOps de código aberto com NetApp - Exemplo de backends Trident para implantações NetApp AIPod 
---
= Exemplo de backends Trident para implantações NetApp AIPod
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de usar o Trident para provisionar dinamicamente recursos de armazenamento no seu cluster Kubernetes, você deve criar um ou mais Trident Backends.  Os exemplos a seguir representam diferentes tipos de backends que você pode querer criar se estiver implantando componentes desta solução em umlink:../infra/ai-aipod-nv-intro.html["NetApp AIPod"^] .  Para obter mais informações sobre backends e, por exemplo, backends para outras plataformas/ambientes, consulte olink:https://docs.netapp.com/us-en/trident/index.html["Documentação do Trident"^] .

. A NetApp recomenda a criação de um Trident Backend habilitado para FlexGroup para seu AIPod.
+
Os comandos de exemplo a seguir mostram a criação de um Trident Backend habilitado para FlexGroup para uma máquina virtual de armazenamento AIPod (SVM).  Este Backend usa o `ontap-nas-flexgroup` driver de armazenamento.  O ONTAP suporta dois tipos principais de volume de dados: FlexVol e FlexGroup.  Os volumes FlexVol têm tamanho limitado (no momento em que este artigo foi escrito, o tamanho máximo depende da implantação específica).  Os volumes FlexGroup , por outro lado, podem ser dimensionados linearmente para até 20 PB e 400 bilhões de arquivos, fornecendo um único namespace que simplifica muito o gerenciamento de dados.  Portanto, os volumes FlexGroup são ideais para cargas de trabalho de IA e ML que dependem de grandes quantidades de dados.

+
Se você estiver trabalhando com uma pequena quantidade de dados e quiser usar volumes FlexVol em vez de volumes FlexGroup , você pode criar Trident Backends que usam o `ontap-nas` driver de armazenamento em vez do `ontap-nas-flexgroup` driver de armazenamento.

+
....
$ cat << EOF > ./trident-backend-aipod-flexgroups-iface1.json
{
    "version": 1,
    "storageDriverName": "ontap-nas-flexgroup",
    "backendName": "aipod-flexgroups-iface1",
    "managementLIF": "10.61.218.100",
    "dataLIF": "192.168.11.11",
    "svm": "ontapai_nfs",
    "username": "admin",
    "password": "ontapai"
}
EOF
$ tridentctl create backend -f ./trident-backend-aipod-flexgroups-iface1.json -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexgroups-iface1 | ontap-nas-flexgroup | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
$ tridentctl get backend -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexgroups-iface1 | ontap-nas-flexgroup | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
....
. A NetApp também recomenda a criação de um Trident Backend habilitado para FlexVol .  Você pode querer usar volumes FlexVol para hospedar aplicativos persistentes, armazenar resultados, saídas, informações de depuração e assim por diante.  Se quiser usar volumes FlexVol , você deve criar um ou mais Trident Backends habilitados para FlexVol .  Os comandos de exemplo a seguir mostram a criação de um único Trident Backend habilitado para FlexVol .


....
$ cat << EOF > ./trident-backend-aipod-flexvols.json
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "backendName": "aipod-flexvols",
    "managementLIF": "10.61.218.100",
    "dataLIF": "192.168.11.11",
    "svm": "ontapai_nfs",
    "username": "admin",
    "password": "ontapai"
}
EOF
$ tridentctl create backend -f ./trident-backend-aipod-flexvols.json -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexvols          | ontap-nas           | 52bdb3b1-13a5-4513-a9c1-52a69657fabe | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
$ tridentctl get backend -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexvols          | ontap-nas           | 52bdb3b1-13a5-4513-a9c1-52a69657fabe | online |       0 |
| aipod-flexgroups-iface1 | ontap-nas-flexgroup | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
....