---
sidebar: sidebar 
permalink: software/ai-osmlops-architecture.html 
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu 
summary: MLOps de código aberto com NetApp - Arquitetura 
---
= Arquitetura
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta solução não depende de hardware específico.  A solução é compatível com qualquer dispositivo de armazenamento físico, instância definida por software ou serviço de nuvem da NetApp suportado pelo NetApp Trident.  Exemplos incluem um sistema de armazenamento NetApp AFF , Amazon FSx ONTAP, Azure NetApp Files, Google Cloud NetApp Volumes ou uma instância NetApp Cloud Volumes ONTAP .  Além disso, a solução pode ser implementada em qualquer cluster do Kubernetes, desde que a versão do Kubernetes usada seja compatível com o NetApp Trident e os outros componentes da solução que estão sendo implementados.  Para obter uma lista de versões do Kubernetes suportadas pelo Trident, consulte https://docs.netapp.com/us-en/trident/index.html["Documentação do Trident"^] .  Consulte as tabelas a seguir para obter detalhes sobre os ambientes que foram usados para validar os vários componentes desta solução.



== Ambiente de validação do Apache Airflow

|===
| Componente de software | Versão 


| Apache Airflow | 2.0.1, implantado vialink:https://artifacthub.io/packages/helm/airflow-helm/airflow["Gráfico do Apache Airflow Helm"^] 8.0.8 


| Kubernetes | 1,18 


| NetApp Trident | 21,01 
|===


== Ambiente de validação JupyterHub

|===
| Componente de software | Versão 


| JupyterHub | 4.1.5, implantado vialink:https://hub.jupyter.org/helm-chart/["Gráfico do JupyterHub Helm"^] 3.3.7 


| Kubernetes | 1,29 


| NetApp Trident | 24,02 
|===


== Ambiente de Validação MLflow

|===
| Componente de software | Versão 


| Fluxo de ML | 2.14.1, implantado vialink:https://artifacthub.io/packages/helm/bitnami/mlflow["Gráfico Helm do MLflow"^] 1.4.12 


| Kubernetes | 1,29 


| NetApp Trident | 24,02 
|===


== Ambiente de Validação Kubeflow

|===
| Componente de software | Versão 


| Fluxo de cubo | 1.7, implantado vialink:https://www.deploykf.org["implantarKF"^] 0.1.1 


| Kubernetes | 1,26 


| NetApp Trident | 23,07 
|===


== Apoiar

A NetApp não oferece suporte empresarial para Apache Airflow, JupyterHub, MLflow, Kubeflow ou Kubernetes.  Se você estiver interessado em uma plataforma MLOps totalmente suportada,link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us["entre em contato com a NetApp"^] sobre soluções MLOps totalmente suportadas que a NetApp oferece em conjunto com parceiros.
